# Voice Configuration File
# Simple voice presets for Kokoro TTS

voices:
  # American English Voices
  bella:
    voice: "af_bella"
    speed: 1.0
  
  nicole:
    voice: "af_nicole"
    speed: 1.0
  
  alloy:
    voice: "af_alloy"
    speed: 1.0
  
  aoede:
    voice: "af_aoede"
    speed: 1.0
  
  ada:
    voice: "af_aoede"
    speed: 1.5
    # Stinger sound effects (optional)
    # Paths are relative to the project root
    stingers:
      alert: tmp/alert.wav
      error: tmp/error.wav
    # Default stinger to play when none specified via CLI
    default_stinger: alert
  
  kore:
    voice: "af_kore"
    speed: 1.0
  
  sarah:
    voice: "af_sarah"
    speed: 1.0
  
  nova:
    voice: "af_nova"
    speed: 1.0
  
  jessica:
    voice: "af_jessica"
    speed: 1.0
  
  river:
    voice: "af_river"
    speed: 1.0
  
  sky:
    voice: "af_sky"
    speed: 1.0
  
  heart:
    voice: "af_heart"
    speed: 1.0
  
  fenrir:
    voice: "am_fenrir"
    speed: 1.0
  
  michael:
    voice: "am_michael"
    speed: 1.0
  
  puck:
    voice: "am_puck"
    speed: 1.0
  
  echo:
    voice: "am_echo"
    speed: 1.0
  
  eric:
    voice: "am_eric"
    speed: 1.0
  
  liam:
    voice: "am_liam"
    speed: 1.0
  
  onyx:
    voice: "am_onyx"
    speed: 1.0
  
  santa:
    voice: "am_santa"
    speed: 1.0
  
  adam:
    voice: "am_adam"
    speed: 1.0
  
  # British English Voices
  emma:
    voice: "bf_emma"
    speed: 1.0
  
  isabella:
    voice: "bf_isabella"
    speed: 1.0
  
  fable:
    voice: "bm_fable"
    speed: 1.0
  
  george:
    voice: "bm_george"
    speed: 1.0
  
  lewis:
    voice: "bm_lewis"
    speed: 1.0
  
  alice:
    voice: "bf_alice"
    speed: 1.0
  
  lily:
    voice: "bf_lily"
    speed: 1.0
  
  daniel:
    voice: "bm_daniel"
    speed: 1.0
