# Voice Configuration File
# Define voice presets with their TTS engines and optional LLM transformations

# LLM Configuration (optional, used for text transformation)
llm:
  backend: "ollama"  # "ollama" or "none"
  model: "llama3.2"
  api_url: "http://localhost:11434/api/chat"
  timeout: 30  # seconds

# Audio output settings
audio:
  sample_rate: 22050
  format: "ogg"  # Output format when saving to file
  auto_play: true  # Play audio by default (unless -o is specified)

# Voice presets
voices:
  # GLaDOS voice - sarcastic AI from Portal
  glados:
    tts_engine: "glados"  # Uses GLaDOS ONNX model
    model_path: "../models/TTS/glados.onnx"
    phonemizer_path: "../models/TTS/phomenizer_en.onnx"
    speed: 1.0
    enable_llm: true
    system_prompt: |
      You are GLaDOS, a sarcastic and cunning artificial intelligence. 
      Transform the user's text to match your signature dry, emotionless, and laconic tone from Portal.
      Your responses should imply an air of superiority, dark humor, and subtle menace.
      Add condescending, darkly humorous commentary while keeping the core message.
      Keep responses concise - 2-3 sentences maximum.
      Never use ALL CAPS as it breaks the TTS engine.
    
  # Kokoro multi-voice support - Bella (female)
  bella:
    tts_engine: "kokoro"
    model_path: "../models/TTS/kokoro-v1.0.fp16.onnx"
    phonemizer_path: "../models/TTS/phomenizer_en.onnx"
    voice: "af_bella"  # Specific voice variant
    speed: 1.0
    enable_llm: false
    
  # Kokoro - Adam (male)
  adam:
    tts_engine: "kokoro"
    model_path: "../models/TTS/kokoro-v1.0.fp16.onnx"
    phonemizer_path: "../models/TTS/phomenizer_en.onnx"
    voice: "am_adam"
    speed: 1.0
    enable_llm: false
  
  # Custom personality: Motivational coach
  coach:
    tts_engine: "kokoro"
    model_path: "../models/TTS/kokoro-v1.0.fp16.onnx"
    phonemizer_path: "../models/TTS/phomenizer_en.onnx"
    voice: "am_adam"
    speed: 1.05
    enable_llm: true
    system_prompt: |
      You are an enthusiastic motivational coach.
      Transform the user's text into an inspiring, energetic message.
      Use phrases like "You've got this!", "Believe in yourself!", etc.
      Keep it short, punchy, and motivating - 2 sentences max.
      
  # Custom personality: Shakespeare
  shakespeare:
    tts_engine: "kokoro"
    model_path: "../models/TTS/kokoro-v1.0.fp16.onnx"
    phonemizer_path: "../models/TTS/phomenizer_en.onnx"
    voice: "am_michael"
    speed: 0.9
    enable_llm: true
    system_prompt: |
      You are William Shakespeare.
      Transform the user's text into Elizabethan English with poetic flair.
      Use "thee", "thou", "thy", etc. Add metaphors and dramatic language.
      Keep it concise but theatrical - 2-3 sentences.
    
  # Neutral voice - no personality, direct TTS
  neutral:
    tts_engine: "kokoro"
    model_path: "../models/TTS/kokoro-v1.0.fp16.onnx"
    phonemizer_path: "../models/TTS/phomenizer_en.onnx"
    voice: "af_bella"
    speed: 1.0
    enable_llm: false
