# Voice Configuration File
# Define voice presets with their TTS engines and optional LLM transformations

# LLM Configuration (optional, used for text transformation)
llm:
  backend: "ollama"  # "ollama" or "none"
  model: "llama3.2"
  api_url: "http://localhost:11434/api/chat"
  timeout: 30  # seconds

# Audio output settings
audio:
  sample_rate: 22050
  format: "ogg"  # Output format when saving to file
  auto_play: true  # Play audio by default (unless -o is specified)

# Voice presets
voices:
  # GLaDOS voice - sarcastic AI from Portal
  glados:
    tts_engine: "glados"  # Uses GLaDOS ONNX model
    model_path: "../../../models/TTS/glados.onnx"
    phonemizer_path: "../../../models/TTS/phomenizer_en.onnx"
    speed: 1.0
    enable_llm: true
    system_prompt: |
      You are GLaDOS, a sarcastic and cunning artificial intelligence. 
      Transform the user's text to match your signature dry, emotionless, and laconic tone from Portal.
      Your responses should imply an air of superiority, dark humor, and subtle menace.
      Add condescending, darkly humorous commentary while keeping the core message.
      Keep responses concise - 2-3 sentences maximum.
      Never use ALL CAPS as it breaks the TTS engine.
    
  # Kokoro multi-voice support - Bella (female)
  kokoro_bella:
    tts_engine: "kokoro"
    model_path: "../../../models/TTS/kokoro-v1.0.fp16.onnx"
    phonemizer_path: "../../../models/TTS/phomenizer_en.onnx"
    voice: "af_bella"  # Specific voice variant
    speed: 1.0
    enable_llm: false
    
  # Kokoro - Adam (male)
  kokoro_adam:
    tts_engine: "kokoro"
    model_path: "../../../models/TTS/kokoro-v1.0.fp16.onnx"
    phonemizer_path: "../../../models/TTS/phomenizer_en.onnx"
    voice: "am_adam"
    speed: 1.0
    enable_llm: false
  
  # Pirate voice - fun personality transformation
  pirate:
    tts_engine: "kokoro"
    model_path: "../../../models/TTS/kokoro-v1.0.fp16.onnx"
    phonemizer_path: "../../../models/TTS/phomenizer_en.onnx"
    voice: "am_adam"
    speed: 0.95
    enable_llm: true
    system_prompt: |
      You are a pirate captain from the golden age of piracy.
      Transform the user's text into pirate speak with phrases like "Arrr", "matey", "ye", "treasure", etc.
      Keep the core message but add pirate flavor and personality.
      Be enthusiastic and adventurous!
      Keep it concise - 2-3 sentences.
  
  # ElevenLabs voice (requires API key)
  elevenlabs:
    tts_engine: "elevenlabs"
    api_key: null  # Set via environment variable ELEVENLABS_API_KEY or here
    voice_id: "21m00Tcm4TlvDq8ikWAM"  # Rachel voice
    model: "eleven_monolingual_v1"
    enable_llm: false
    
  # Neutral voice - no personality, direct TTS
  neutral:
    tts_engine: "kokoro"
    model_path: "../../../models/TTS/kokoro-v1.0.fp16.onnx"
    phonemizer_path: "../../../models/TTS/phomenizer_en.onnx"
    voice: "af_bella"
    speed: 1.0
    enable_llm: false
